version: '3.8'

services:
  marketing-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talos-marketing-site
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      # Mount config.json to allow runtime configuration changes without rebuilding
      - ./config.json:/usr/share/nginx/html/config.json:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.talos.project=marketing-site"
      - "com.talos.version=1.0.0"
      - "com.talos.description=TALOS mAInd Marketing Website"
